### ISSUE TITLE
Is it really not "production ready" as stated in the readme?

### ISSUE THREAD

**Issue by gregjacobs** [dhruvrajvanshi/ts-failable#2]
Hey, this looks really cool and I _love_ the idea of the `run()` function to short-circuit errors in multiple calls which may return failables (something which isn't really addressed in the `neverthrow` package).

Just wondering if you have hit any real limitations in the real world or if I should give it a try.

Thanks!
Greg

**Comment by dhruvrajvanshi** [comment]
Feel free to give it a try. But yeah don't expect any serious support.

I used this in a POC at work and it seemed to work okay. The reason I didn't end up using it because it isn't exactly idiomatic typescript code but that's more for you to decide.

If you find bugs, you can definitely open an issue and I'll try to fix it.

**Comment by dhruvrajvanshi** [comment]
Closing this. See previous comment.
